;(function(){
  const countries = [
    { names:["Afghanistan"],               flagUrl:'https://flagcdn.com/af.svg', capitals:["Kabul"], categories:["Asia"] },
    { names:["Albania"],                   flagUrl:'https://flagcdn.com/al.svg', capitals:["Tirana"], categories:["Europe"] },
    { names:["Algeria"],                   flagUrl:'https://flagcdn.com/dz.svg', capitals:["Algiers"], categories:["Africa"] },
    { names:["Andorra"],                   flagUrl:'https://flagcdn.com/ad.svg', capitals:["Andorra la Vella"], categories:["Europe"] },
    { names:["Angola"],                    flagUrl:'https://flagcdn.com/ao.svg', capitals:["Luanda"], categories:["Africa"] },
    { names:["Antigua And Barbuda"],       flagUrl:'https://flagcdn.com/ag.svg', capitals:["St. John's"], categories:["North America","Small Island"] },
    { names:["Argentina"],                 flagUrl:'https://flagcdn.com/ar.svg', capitals:["Buenos Aires"], categories:["South America"] },
    { names:["Armenia"],                   flagUrl:'https://flagcdn.com/am.svg', capitals:["Yerevan"], categories:["Asia"] },
    { names:["Australia"],                 flagUrl:'https://flagcdn.com/au.svg', capitals:["Canberra"], categories:["Oceania"] },
    { names:["Austria"],                   flagUrl:'https://flagcdn.com/at.svg', capitals:["Vienna"], categories:["Europe"] },
    { names:["Azerbaijan"],                flagUrl:'https://flagcdn.com/az.svg', capitals:["Baku"], categories:["Asia"] },
    { names:["Bahamas", "The Bahamas"],    flagUrl:'https://flagcdn.com/bs.svg', capitals:["Nassau"], categories:["North America","Small Island"] },
    { names:["Bahrain"],                   flagUrl:'https://flagcdn.com/bh.svg', capitals:["Manama"], categories:["Asia"] },
    { names:["Bangladesh"],                flagUrl:'https://flagcdn.com/bd.svg', capitals:["Dhaka"], categories:["Asia"] },
    { names:["Barbados"],                  flagUrl:'https://flagcdn.com/bb.svg', capitals:["Bridgetown"], categories:["North America","Small Island"] },
    { names:["Belarus"],                   flagUrl:'https://flagcdn.com/by.svg', capitals:["Minsk"], categories:["Europe"] },
    { names:["Belgium"],                   flagUrl:'https://flagcdn.com/be.svg', capitals:["Brussels"], categories:["Europe"] },
    { names:["Belize"],                    flagUrl:'https://flagcdn.com/bz.svg', capitals:["Belmopan"], categories:["North America"] },
    { names:["Benin"],                     flagUrl:'https://flagcdn.com/bj.svg', capitals:["Porto-Novo"], categories:["Africa"] },
    { names:["Bhutan"],                    flagUrl:'https://flagcdn.com/bt.svg', capitals:["Thimphu"], categories:["Asia"] },
    { names:["Bolivia"],                   flagUrl:'https://flagcdn.com/bo.svg', capitals:["Sucre","La Paz"], categories:["South America"] },
    { names:["Bosnia And Herzegovina"],    flagUrl:'https://flagcdn.com/ba.svg', capitals:["Sarajevo"], categories:["Europe"] },
    { names:["Botswana"],                  flagUrl:'https://flagcdn.com/bw.svg', capitals:["Gaborone"], categories:["Africa"] },
    { names:["Brazil"],                    flagUrl:'https://flagcdn.com/br.svg', capitals:["Brasília"], categories:["South America"] },
    { names:["Brunei"],                    flagUrl:'https://flagcdn.com/bn.svg', capitals:["Bandar Seri Begawan"], categories:["Asia"] },
    { names:["Bulgaria"],                  flagUrl:'https://flagcdn.com/bg.svg', capitals:["Sofia"], categories:["Europe"] },
    { names:["Burkina Faso"],              flagUrl:'https://flagcdn.com/bf.svg', capitals:["Ouagadougou"], categories:["Africa"] },
    { names:["Burundi"],                   flagUrl:'https://flagcdn.com/bi.svg', capitals:["Gitega"], categories:["Africa"] },
    { names:["Côte d'Ivoire","Ivory Coast"],flagUrl:'https://flagcdn.com/ci.svg', capitals:["Yamoussoukro"], categories:["Africa"] },
    { names:["Cabo Verde"],                flagUrl:'https://flagcdn.com/cv.svg', capitals:["Praia"], categories:["Africa","Small Island"] },
    { names:["Cambodia"],                  flagUrl:'https://flagcdn.com/kh.svg', capitals:["Phnom Penh"], categories:["Asia"] },
    { names:["Cameroon"],                  flagUrl:'https://flagcdn.com/cm.svg', capitals:["Yaoundé"], categories:["Africa"] },
    { names:["Canada"],                    flagUrl:'https://flagcdn.com/ca.svg', capitals:["Ottawa"], categories:["North America"] },
    { names:["Central African Republic","CAR"],flagUrl:'https://flagcdn.com/cf.svg', capitals:["Bangui"], categories:["Africa"] },
    { names:["Chad"],                      flagUrl:'https://flagcdn.com/td.svg', capitals:["N'Djamena"], categories:["Africa"] },
    { names:["Chile"],                     flagUrl:'https://flagcdn.com/cl.svg', capitals:["Santiago"], categories:["South America"] },
    { names:["China", "PRC", "People's Republic of China"], flagUrl:'https://flagcdn.com/cn.svg', capitals:["Beijing"], categories:["Asia"] },
    { names:["Colombia"],                  flagUrl:'https://flagcdn.com/co.svg', capitals:["Bogotá"], categories:["South America"] },
    { names:["Comoros"],                   flagUrl:'https://flagcdn.com/km.svg', capitals:["Moroni"], categories:["Africa","Small Island"] },
    { names:["Costa Rica"],                flagUrl:'https://flagcdn.com/cr.svg', capitals:["San José"], categories:["North America"] },
    { names:["Croatia"],                   flagUrl:'https://flagcdn.com/hr.svg', capitals:["Zagreb"], categories:["Europe"] },
    { names:["Cuba"],                      flagUrl:'https://flagcdn.com/cu.svg', capitals:["Havana"], categories:["North America","Small Island"] },
    { names:["Cyprus"],                    flagUrl:'https://flagcdn.com/cy.svg', capitals:["Nicosia"], categories:["Asia","Small Island"] },
    { names:["Czech Republic","Czechia"],  flagUrl:'https://flagcdn.com/cz.svg', capitals:["Prague"], categories:["Europe"] },
    { names:["Democratic Republic Of The Congo","DRC", "DR Congo"], flagUrl:'https://flagcdn.com/cd.svg', capitals:["Kinshasa"], categories:["Africa"] },
    { names:["Denmark"],                   flagUrl:'https://flagcdn.com/dk.svg', capitals:["Copenhagen"], categories:["Europe"] },
    { names:["Djibouti"],                  flagUrl:'https://flagcdn.com/dj.svg', capitals:["Djibouti"], categories:["Africa"] },
    { names:["Dominica"],                  flagUrl:'https://flagcdn.com/dm.svg', capitals:["Roseau"], categories:["North America","Small Island"] },
    { names:["Dominican Republic"],        flagUrl:'https://flagcdn.com/do.svg', capitals:["Santo Domingo"], categories:["North America","Small Island"] },
    { names:["Ecuador"],                   flagUrl:'https://flagcdn.com/ec.svg', capitals:["Quito"], categories:["South America"] },
    { names:["Egypt"],                     flagUrl:'https://flagcdn.com/eg.svg', capitals:["Cairo"], categories:["Africa"] },
    { names:["El Salvador"],               flagUrl:'https://flagcdn.com/sv.svg', capitals:["San Salvador"], categories:["North America"] },
    { names:["Equatorial Guinea"],         flagUrl:'https://flagcdn.com/gq.svg', capitals:["Malabo","Oyala"], categories:["Africa"] },
    { names:["Eritrea"],                   flagUrl:'https://flagcdn.com/er.svg', capitals:["Asmara"], categories:["Africa"] },
    { names:["Estonia"],                   flagUrl:'https://flagcdn.com/ee.svg', capitals:["Tallinn"], categories:["Europe"] },
    { names:["Eswatini", "Swaziland"],     flagUrl:'https://flagcdn.com/sz.svg', capitals:["Mbabane","Lobamba"], categories:["Africa"] },
    { names:["Ethiopia"],                  flagUrl:'https://flagcdn.com/et.svg', capitals:["Addis Ababa"], categories:["Africa"] },
    { names:["Fiji"],                      flagUrl:'https://flagcdn.com/fj.svg', capitals:["Suva"], categories:["Oceania","Small Island"] },
    { names:["Finland"],                   flagUrl:'https://flagcdn.com/fi.svg', capitals:["Helsinki"], categories:["Europe"] },
    { names:["France"],                    flagUrl:'https://flagcdn.com/fr.svg', capitals:["Paris"], categories:["Europe"] },
    { names:["Gabon"],                     flagUrl:'https://flagcdn.com/ga.svg', capitals:["Libreville"], categories:["Africa"] },
    { names:["Gambia", "The Gambia"],      flagUrl:'https://flagcdn.com/gm.svg', capitals:["Banjul"], categories:["Africa"] },
    { names:["Georgia"],                   flagUrl:'https://flagcdn.com/ge.svg', capitals:["Tbilisi"], categories:["Asia"] },
    { names:["Germany"],                   flagUrl:'https://flagcdn.com/de.svg', capitals:["Berlin"], categories:["Europe"] },
    { names:["Ghana"],                     flagUrl:'https://flagcdn.com/gh.svg', capitals:["Accra"], categories:["Africa"] },
    { names:["Greece"],                    flagUrl:'https://flagcdn.com/gr.svg', capitals:["Athens"], categories:["Europe"] },
    { names:["Grenada"],                   flagUrl:'https://flagcdn.com/gd.svg', capitals:["St. George's"], categories:["North America"] },
    { names:["Guatemala"],                 flagUrl:'https://flagcdn.com/gt.svg', capitals:["Guatemala City"], categories:["North America"] },
    { names:["Guinea"],                    flagUrl:'https://flagcdn.com/gn.svg', capitals:["Conakry"], categories:["Africa"] },
    { names:["Guinea-Bissau"],             flagUrl:'https://flagcdn.com/gw.svg', capitals:["Bissau"], categories:["Africa"] },
    { names:["Guyana"],                    flagUrl:'https://flagcdn.com/gy.svg', capitals:["Georgetown"], categories:["South America"] },
    { names:["Haiti"],                     flagUrl:'https://flagcdn.com/ht.svg', capitals:["Port-au-Prince"], categories:["North America"] },
    { names:["Honduras"],                  flagUrl:'https://flagcdn.com/hn.svg', capitals:["Tegucigalpa"], categories:["North America"] },
    { names:["Hungary"],                   flagUrl:'https://flagcdn.com/hu.svg', capitals:["Budapest"], categories:["Europe"] },
    { names:["Iceland"],                   flagUrl:'https://flagcdn.com/is.svg', capitals:["Reykjavík"], categories:["Europe"] },
    { names:["India"],                     flagUrl:'https://flagcdn.com/in.svg', capitals:["New Delhi"], categories:["Asia"] },
    { names:["Indonesia"],                 flagUrl:'https://flagcdn.com/id.svg', capitals:["Jakarta"], categories:["Asia"] },
    { names:["Iran"],                      flagUrl:'https://flagcdn.com/ir.svg', capitals:["Tehran"], categories:["Asia"] },
    { names:["Iraq"],                      flagUrl:'https://flagcdn.com/iq.svg', capitals:["Baghdad"], categories:["Asia"] },
    { names:["Ireland"],                   flagUrl:'https://flagcdn.com/ie.svg', capitals:["Dublin"], categories:["Europe"] },
    { names:["Israel"],                    flagUrl:'https://flagcdn.com/il.svg', capitals:["Jerusalem"], categories:["Asia"] },
    { names:["Italy"],                     flagUrl:'https://flagcdn.com/it.svg', capitals:["Rome"], categories:["Europe"] },
    { names:["Jamaica"],                   flagUrl:'https://flagcdn.com/jm.svg', capitals:["Kingston"], categories:["North America"] },
    { names:["Japan"],                     flagUrl:'https://flagcdn.com/jp.svg', capitals:["Tokyo"], categories:["Asia"] },
    { names:["Jordan"],                    flagUrl:'https://flagcdn.com/jo.svg', capitals:["Amman"], categories:["Asia"] },
    { names:["Kazakhstan"],                flagUrl:'https://flagcdn.com/kz.svg', capitals:["Astana"], categories:["Asia"] },
    { names:["Kenya"],                     flagUrl:'https://flagcdn.com/ke.svg', capitals:["Nairobi"], categories:["Africa"] },
    { names:["Kiribati"],                  flagUrl:'https://flagcdn.com/ki.svg', capitals:["Tarawa"], categories:["Oceania","Small Island"] },
    { names:["Kuwait"],                    flagUrl:'https://flagcdn.com/kw.svg', capitals:["Kuwait City"], categories:["Asia"] },
    { names:["Kyrgyzstan"],                flagUrl:'https://flagcdn.com/kg.svg', capitals:["Bishkek"], categories:["Asia"] },
    { names:["Laos"],                      flagUrl:'https://flagcdn.com/la.svg', capitals:["Vientiane"], categories:["Asia"] },
    { names:["Latvia"],                    flagUrl:'https://flagcdn.com/lv.svg', capitals:["Riga"], categories:["Europe"] },
    { names:["Lebanon"],                   flagUrl:'https://flagcdn.com/lb.svg', capitals:["Beirut"], categories:["Asia"] },
    { names:["Lesotho"],                   flagUrl:'https://flagcdn.com/ls.svg', capitals:["Maseru"], categories:["Africa"] },
    { names:["Liberia"],                   flagUrl:'https://flagcdn.com/lr.svg', capitals:["Monrovia"], categories:["Africa"] },
    { names:["Libya"],                     flagUrl:'https://flagcdn.com/ly.svg', capitals:["Tripoli"], categories:["Africa"] },
    { names:["Liechtenstein"],             flagUrl:'https://flagcdn.com/li.svg', capitals:["Vaduz"], categories:["Europe"] },
    { names:["Lithuania"],                 flagUrl:'https://flagcdn.com/lt.svg', capitals:["Vilnius"], categories:["Europe"] },
    { names:["Luxembourg"],                flagUrl:'https://flagcdn.com/lu.svg', capitals:["Luxembourg City"], categories:["Europe"] },
    { names:["Madagascar"],                flagUrl:'https://flagcdn.com/mg.svg', capitals:["Antananarivo"], categories:["Africa"] },
    { names:["Malawi"],                    flagUrl:'https://flagcdn.com/mw.svg', capitals:["Lilongwe"], categories:["Africa"] },
    { names:["Malaysia"],                  flagUrl:'https://flagcdn.com/my.svg', capitals:["Kuala Lumpur"], categories:["Asia"] },
    { names:["Maldives"],                  flagUrl:'https://flagcdn.com/mv.svg', capitals:["Malé"], categories:["Asia","Small Island"] },
    { names:["Mali"],                      flagUrl:'https://flagcdn.com/ml.svg', capitals:["Bamako"], categories:["Africa"] },
    { names:["Malta"],                     flagUrl:'https://flagcdn.com/mt.svg', capitals:["Valletta"], categories:["Europe","Small Island"] },
    { names:["Marshall Islands"],          flagUrl:'https://flagcdn.com/mh.svg', capitals:["Majuro"], categories:["Oceania","Small Island"] },
    { names:["Mauritania"],                flagUrl:'https://flagcdn.com/mr.svg', capitals:["Nouakchott"], categories:["Africa"] },
    { names:["Mauritius"],                 flagUrl:'https://flagcdn.com/mu.svg', capitals:["Port Louis"], categories:["Africa"] },
    { names:["Mexico"],                    flagUrl:'https://flagcdn.com/mx.svg', capitals:["Mexico City"], categories:["North America"] },
    { names:["Micronesia"],                flagUrl:'https://flagcdn.com/fm.svg', capitals:["Palikir"], categories:["Oceania","Small Island"] },
    { names:["Moldova"],                   flagUrl:'https://flagcdn.com/md.svg', capitals:["Chișinău"], categories:["Europe"] },
    { names:["Monaco"],                    flagUrl:'https://flagcdn.com/mc.svg', capitals:["Monaco"], categories:["Europe"] },
    { names:["Mongolia"],                  flagUrl:'https://flagcdn.com/mn.svg', capitals:["Ulaanbaatar"], categories:["Asia"] },
    { names:["Montenegro"],                flagUrl:'https://flagcdn.com/me.svg', capitals:["Podgorica"], categories:["Europe"] },
    { names:["Morocco"],                   flagUrl:'https://flagcdn.com/ma.svg', capitals:["Rabat"], categories:["Africa"] },
    { names:["Mozambique"],                flagUrl:'https://flagcdn.com/mz.svg', capitals:["Maputo"], categories:["Africa"] },
    { names:["Myanmar"],                   flagUrl:'https://flagcdn.com/mm.svg', capitals:["Naypyidaw"], categories:["Asia"] },
    { names:["Namibia"],                   flagUrl:'https://flagcdn.com/na.svg', capitals:["Windhoek"], categories:["Africa"] },
    { names:["Nauru"],                     flagUrl:'https://flagcdn.com/nr.svg', capitals:["Yaren"], categories:["Oceania","Small Island"] },
    { names:["Nepal"],                     flagUrl:'https://flagcdn.com/np.svg', capitals:["Kathmandu"], categories:["Asia"] },
    { names:["Netherlands"],               flagUrl:'https://flagcdn.com/nl.svg', capitals:["Amsterdam"], categories:["Europe"] },
    { names:["New Zealand"],               flagUrl:'https://flagcdn.com/nz.svg', capitals:["Wellington"], categories:["Oceania"] },
    { names:["Nicaragua"],                 flagUrl:'https://flagcdn.com/ni.svg', capitals:["Managua"], categories:["North America"] },
    { names:["Niger"],                     flagUrl:'https://flagcdn.com/ne.svg', capitals:["Niamey"], categories:["Africa"] },
    { names:["Nigeria"],                   flagUrl:'https://flagcdn.com/ng.svg', capitals:["Abuja"], categories:["Africa"] },
    { names:["North Korea"],               flagUrl:'https://flagcdn.com/kp.svg', capitals:["Pyongyang"], categories:["Asia"] },
    { names:["North Macedonia"],           flagUrl:'https://flagcdn.com/mk.svg', capitals:["Skopje"], categories:["Europe"] },
    { names:["Norway"],                    flagUrl:'https://flagcdn.com/no.svg', capitals:["Oslo"], categories:["Europe"] },
    { names:["Oman"],                      flagUrl:'https://flagcdn.com/om.svg', capitals:["Muscat"], categories:["Asia"] },
    { names:["Pakistan"],                  flagUrl:'https://flagcdn.com/pk.svg', capitals:["Islamabad"], categories:["Asia"] },
    { names:["Palau"],                     flagUrl:'https://flagcdn.com/pw.svg', capitals:["Ngerulmud"], categories:["Oceania","Small Island"] },
    { names:["Panama"],                    flagUrl:'https://flagcdn.com/pa.svg', capitals:["Panama City"], categories:["North America"] },
    { names:["Papua New Guinea"],          flagUrl:'https://flagcdn.com/pg.svg', capitals:["Port Moresby"], categories:["Oceania"] },
    { names:["Paraguay"],                  flagUrl:'https://flagcdn.com/py.svg', capitals:["Asunción"], categories:["South America"] },
    { names:["Peru"],                      flagUrl:'https://flagcdn.com/pe.svg', capitals:["Lima"], categories:["South America"] },
    { names:["Philippines"],               flagUrl:'https://flagcdn.com/ph.svg', capitals:["Manila"], categories:["Asia"] },
    { names:["Poland"],                    flagUrl:'https://flagcdn.com/pl.svg', capitals:["Warsaw"], categories:["Europe"] },
    { names:["Portugal"],                  flagUrl:'https://flagcdn.com/pt.svg', capitals:["Lisbon"], categories:["Europe"] },
    { names:["Qatar"],                     flagUrl:'https://flagcdn.com/qa.svg', capitals:["Doha"], categories:["Asia"] },
    { names:["Republic Of The Congo"],     flagUrl:'https://flagcdn.com/cg.svg', capitals:["Brazzaville"], categories:["Africa"] },
    { names:["Romania"],                   flagUrl:'https://flagcdn.com/ro.svg', capitals:["Bucharest"], categories:["Europe"] },
    { names:["Russia"],                    flagUrl:'https://flagcdn.com/ru.svg', capitals:["Moscow"], categories:["Europe"] },
    { names:["Rwanda"],                    flagUrl:'https://flagcdn.com/rw.svg', capitals:["Kigali"], categories:["Africa"] },
    { names:["Saint Kitts And Nevis"],     flagUrl:'https://flagcdn.com/kn.svg', capitals:["Basseterre"], categories:["North America","Small Island"] },
    { names:["Saint Lucia"],               flagUrl:'https://flagcdn.com/lc.svg', capitals:["Castries"], categories:["North America","Small Island"] },
    { names:["Saint Vincent And The Grenadines"],flagUrl:'https://flagcdn.com/vc.svg', capitals:["Kingstown"], categories:["North America","Small Island"] },
    { names:["Samoa"],                     flagUrl:'https://flagcdn.com/ws.svg', capitals:["Apia"], categories:["Oceania","Small Island"] },
    { names:["San Marino"],                flagUrl:'https://flagcdn.com/sm.svg', capitals:["San Marino"], categories:["Europe"] },
    { names:["Sao Tome And Principe"],     flagUrl:'https://flagcdn.com/st.svg', capitals:["São Tomé"], categories:["Africa","Small Island"] },
    { names:["Saudi Arabia"],              flagUrl:'https://flagcdn.com/sa.svg', capitals:["Riyadh"], categories:["Asia"] },
    { names:["Senegal"],                   flagUrl:'https://flagcdn.com/sn.svg', capitals:["Dakar"], categories:["Africa"] },
    { names:["Serbia"],                    flagUrl:'https://flagcdn.com/rs.svg', capitals:["Belgrade"], categories:["Europe"] },
    { names:["Seychelles"],                flagUrl:'https://flagcdn.com/sc.svg', capitals:["Victoria"], categories:["Africa","Small Island"] },
    { names:["Sierra Leone"],              flagUrl:'https://flagcdn.com/sl.svg', capitals:["Freetown"], categories:["Africa"] },
    { names:["Singapore"],                 flagUrl:'https://flagcdn.com/sg.svg', capitals:["Singapore"], categories:["Asia"] },
    { names:["Slovakia"],                  flagUrl:'https://flagcdn.com/sk.svg', capitals:["Bratislava"], categories:["Europe"] },
    { names:["Slovenia"],                  flagUrl:'https://flagcdn.com/si.svg', capitals:["Ljubljana"], categories:["Europe"] },
    { names:["Solomon Islands"],           flagUrl:'https://flagcdn.com/sb.svg', capitals:["Honiara"], categories:["Oceania","Small Island"] },
    { names:["Somalia"],                   flagUrl:'https://flagcdn.com/so.svg', capitals:["Mogadishu"], categories:["Africa"] },
    { names:["South Africa"],              flagUrl:'https://flagcdn.com/za.svg', capitals:["Pretoria","Bloemfontein","Cape Town"], categories:["Africa"] },
    { names:["South Korea"],               flagUrl:'https://flagcdn.com/kr.svg', capitals:["Seoul"], categories:["Asia"] },
    { names:["South Sudan"],               flagUrl:'https://flagcdn.com/ss.svg', capitals:["Juba"], categories:["Africa"] },
    { names:["Spain"],                     flagUrl:'https://flagcdn.com/es.svg', capitals:["Madrid"], categories:["Europe"] },
    { names:["Sri Lanka"],                 flagUrl:'https://flagcdn.com/lk.svg', capitals:["Sri Jayawardenepura Kotte","Colombo"], categories:["Asia"] },
    { names:["Sudan"],                     flagUrl:'https://flagcdn.com/sd.svg', capitals:["Khartoum"], categories:["Africa"] },
    { names:["Suriname"],                  flagUrl:'https://flagcdn.com/sr.svg', capitals:["Paramaribo"], categories:["South America"] },
    { names:["Sweden"],                    flagUrl:'https://flagcdn.com/se.svg', capitals:["Stockholm"], categories:["Europe"] },
    { names:["Switzerland"],               flagUrl:'https://flagcdn.com/ch.svg', capitals:["Bern"], categories:["Europe"] },
    { names:["Syria"],                     flagUrl:'https://flagcdn.com/sy.svg', capitals:["Damascus"], categories:["Asia"] },
    { names:["Tajikistan"],                flagUrl:'https://flagcdn.com/tj.svg', capitals:["Dushanbe"], categories:["Asia"] },
    { names:["Tanzania"],                  flagUrl:'https://flagcdn.com/tz.svg', capitals:["Dodoma"], categories:["Africa"] },
    { names:["Thailand"],                  flagUrl:'https://flagcdn.com/th.svg', capitals:["Bangkok"], categories:["Asia"] },
    { names:["Timor-Leste", "East Timor"],               flagUrl:'https://flagcdn.com/tl.svg', capitals:["Dili"], categories:["Asia","Small Island"] },
    { names:["Togo"],                      flagUrl:'https://flagcdn.com/tg.svg', capitals:["Lomé"], categories:["Africa"] },
    { names:["Tonga"],                     flagUrl:'https://flagcdn.com/to.svg', capitals:["Nuku'alofa"], categories:["Oceania","Small Island"] },
    { names:["Trinidad And Tobago"],       flagUrl:'https://flagcdn.com/tt.svg', capitals:["Port of Spain"], categories:["North America","Small Island"] },
    { names:["Tunisia"],                   flagUrl:'https://flagcdn.com/tn.svg', capitals:["Tunis"], categories:["Africa"] },
    { names:["Turkey"],                    flagUrl:'https://flagcdn.com/tr.svg', capitals:["Ankara"], categories:["Asia"] },
    { names:["Turkmenistan"],              flagUrl:'https://flagcdn.com/tm.svg', capitals:["Ashgabat"], categories:["Asia"] },
    { names:["Tuvalu"],                    flagUrl:'https://flagcdn.com/tv.svg', capitals:["Funafuti"], categories:["Oceania","Small Island"] },
    { names:["Uganda"],                    flagUrl:'https://flagcdn.com/ug.svg', capitals:["Kampala"], categories:["Africa"] },
    { names:["Ukraine"],                   flagUrl:'https://flagcdn.com/ua.svg', capitals:["Kyiv"], categories:["Europe"] },
    { names:["United Arab Emirates","UAE"],flagUrl:'https://flagcdn.com/ae.svg', capitals:["Abu Dhabi"], categories:["Asia"] },
    { names:["United Kingdom","UK"],       flagUrl:'https://flagcdn.com/gb.svg', capitals:["London"], categories:["Europe"] },
    { names:["United States Of America","USA", "US"],flagUrl:'https://flagcdn.com/us.svg', capitals:["Washington D.C."], categories:["North America"] },
    { names:["Uruguay"],                   flagUrl:'https://flagcdn.com/uy.svg', capitals:["Montevideo"], categories:["South America"] },
    { names:["Uzbekistan"],                flagUrl:'https://flagcdn.com/uz.svg', capitals:["Tashkent"], categories:["Asia"] },
    { names:["Vanuatu"],                   flagUrl:'https://flagcdn.com/vu.svg', capitals:["Port Vila"], categories:["Oceania","Small Island"] },
    { names:["Venezuela"],                 flagUrl:'https://flagcdn.com/ve.svg', capitals:["Caracas"], categories:["South America"] },
    { names:["Vietnam", "Viet Nam"],       flagUrl:'https://flagcdn.com/vn.svg', capitals:["Hanoi"], categories:["Asia"] },
    { names:["Yemen"],                     flagUrl:'https://flagcdn.com/ye.svg', capitals:["Sana'a"], categories:["Asia"] },
    { names:["Zambia"],                    flagUrl:'https://flagcdn.com/zm.svg', capitals:["Lusaka"], categories:["Africa"] },
    { names:["Zimbabwe"],                  flagUrl:'https://flagcdn.com/zw.svg', capitals:["Harare"], categories:["Africa"] },
    { names:["Taiwan", "Chinese Taipei", "ROC", "Republic of China"], flagUrl:'https://flagcdn.com/tw.svg', capitals:["Taipei"], categories:["Asia"] },
    { names:["Kosovo"],                    flagUrl:'https://flagcdn.com/xk.svg', capitals:["Pristina"], categories:["Europe"] },
    { names:["Palestine"],                 flagUrl:'https://flagcdn.com/ps.svg', capitals:["East Jerusalem","Ramallah"], categories:["Asia"] }
  ];
  window.countries = countries;
})();
