;(function(){
  const countries = [
    { names:["Afghanistan"],               flagUrl:'https://flagcdn.com/w320/af.png', capitals:["Kabul"] },
    { names:["Albania"],                   flagUrl:'https://flagcdn.com/w320/al.png', capitals:["Tirana"] },
    { names:["Algeria"],                   flagUrl:'https://flagcdn.com/w320/dz.png', capitals:["Algiers"] },
    { names:["Andorra"],                   flagUrl:'https://flagcdn.com/w320/ad.png', capitals:["Andorra la Vella"] },
    { names:["Angola"],                    flagUrl:'https://flagcdn.com/w320/ao.png', capitals:["Luanda"] },
    { names:["Antigua And Barbuda"],       flagUrl:'https://flagcdn.com/w320/ag.png', capitals:["St. John's"] },
    { names:["Argentina"],                 flagUrl:'https://flagcdn.com/w320/ar.png', capitals:["Buenos Aires"] },
    { names:["Armenia"],                   flagUrl:'https://flagcdn.com/w320/am.png', capitals:["Yerevan"] },
    { names:["Australia"],                 flagUrl:'https://flagcdn.com/w320/au.png', capitals:["Canberra"] },
    { names:["Austria"],                   flagUrl:'https://flagcdn.com/w320/at.png', capitals:["Vienna"] },
    { names:["Azerbaijan"],                flagUrl:'https://flagcdn.com/w320/az.png', capitals:["Baku"] },
    { names:["Bahamas"],                   flagUrl:'https://flagcdn.com/w320/bs.png', capitals:["Nassau"] },
    { names:["Bahrain"],                   flagUrl:'https://flagcdn.com/w320/bh.png', capitals:["Manama"] },
    { names:["Bangladesh"],                flagUrl:'https://flagcdn.com/w320/bd.png', capitals:["Dhaka"] },
    { names:["Barbados"],                  flagUrl:'https://flagcdn.com/w320/bb.png', capitals:["Bridgetown"] },
    { names:["Belarus"],                   flagUrl:'https://flagcdn.com/w320/by.png', capitals:["Minsk"] },
    { names:["Belgium"],                   flagUrl:'https://flagcdn.com/w320/be.png', capitals:["Brussels"] },
    { names:["Belize"],                    flagUrl:'https://flagcdn.com/w320/bz.png', capitals:["Belmopan"] },
    { names:["Benin"],                     flagUrl:'https://flagcdn.com/w320/bj.png', capitals:["Porto-Novo"] },
    { names:["Bhutan"],                    flagUrl:'https://flagcdn.com/w320/bt.png', capitals:["Thimphu"] },
    { names:["Bolivia"],                   flagUrl:'https://flagcdn.com/w320/bo.png', capitals:["Sucre","La Paz"] },
    { names:["Bosnia And Herzegovina"],    flagUrl:'https://flagcdn.com/w320/ba.png', capitals:["Sarajevo"] },
    { names:["Botswana"],                  flagUrl:'https://flagcdn.com/w320/bw.png', capitals:["Gaborone"] },
    { names:["Brazil"],                    flagUrl:'https://flagcdn.com/w320/br.png', capitals:["Brasília"] },
    { names:["Brunei"],                    flagUrl:'https://flagcdn.com/w320/bn.png', capitals:["Bandar Seri Begawan"] },
    { names:["Bulgaria"],                  flagUrl:'https://flagcdn.com/w320/bg.png', capitals:["Sofia"] },
    { names:["Burkina Faso"],              flagUrl:'https://flagcdn.com/w320/bf.png', capitals:["Ouagadougou"] },
    { names:["Burundi"],                   flagUrl:'https://flagcdn.com/w320/bi.png', capitals:["Gitega"] },
    { names:["Côte D'ivoire","Ivory Coast"], flagUrl:'https://flagcdn.com/w320/ci.png', capitals:["Yamoussoukro"] },
    { names:["Cabo Verde"],                flagUrl:'https://flagcdn.com/w320/cv.png', capitals:["Praia"] },
    { names:["Cambodia"],                  flagUrl:'https://flagcdn.com/w320/kh.png', capitals:["Phnom Penh"] },
    { names:["Cameroon"],                  flagUrl:'https://flagcdn.com/w320/cm.png', capitals:["Yaoundé"] },
    { names:["Canada"],                    flagUrl:'https://flagcdn.com/w320/ca.png', capitals:["Ottawa"] },
    { names:["Central African Republic","CAR"], flagUrl:'https://flagcdn.com/w320/cf.png', capitals:["Bangui"] },
    { names:["Chad"],                      flagUrl:'https://flagcdn.com/w320/td.png', capitals:["N'Djamena"] },
    { names:["Chile"],                     flagUrl:'https://flagcdn.com/w320/cl.png', capitals:["Santiago"] },
    { names:["China"],                     flagUrl:'https://flagcdn.com/w320/cn.png', capitals:["Beijing"] },
    { names:["Colombia"],                  flagUrl:'https://flagcdn.com/w320/co.png', capitals:["Bogotá"] },
    { names:["Comoros"],                   flagUrl:'https://flagcdn.com/w320/km.png', capitals:["Moroni"] },
    { names:["Costa Rica"],                flagUrl:'https://flagcdn.com/w320/cr.png', capitals:["San José"] },
    { names:["Croatia"],                   flagUrl:'https://flagcdn.com/w320/hr.png', capitals:["Zagreb"] },
    { names:["Cuba"],                      flagUrl:'https://flagcdn.com/w320/cu.png', capitals:["Havana"] },
    { names:["Cyprus"],                    flagUrl:'https://flagcdn.com/w320/cy.png', capitals:["Nicosia"] },
    { names:["Czech Republic","Czechia"],  flagUrl:'https://flagcdn.com/w320/cz.png', capitals:["Prague"] },
    { names:["Democratic Republic Of The Congo","DRC"], flagUrl:'https://flagcdn.com/w320/cd.png', capitals:["Kinshasa"] },
    { names:["Denmark"],                   flagUrl:'https://flagcdn.com/w320/dk.png', capitals:["Copenhagen"] },
    { names:["Djibouti"],                  flagUrl:'https://flagcdn.com/w320/dj.png', capitals:["Djibouti"] },
    { names:["Dominica"],                  flagUrl:'https://flagcdn.com/w320/dm.png', capitals:["Roseau"] },
    { names:["Dominican Republic"],        flagUrl:'https://flagcdn.com/w320/do.png', capitals:["Santo Domingo"] },
    { names:["Ecuador"],                   flagUrl:'https://flagcdn.com/w320/ec.png', capitals:["Quito"] },
    { names:["Egypt"],                     flagUrl:'https://flagcdn.com/w320/eg.png', capitals:["Cairo"] },
    { names:["El Salvador"],               flagUrl:'https://flagcdn.com/w320/sv.png', capitals:["San Salvador"] },
    { names:["Equatorial Guinea"],         flagUrl:'https://flagcdn.com/w320/gq.png', capitals:["Malabo","Oyala"] },
    { names:["Eritrea"],                   flagUrl:'https://flagcdn.com/w320/er.png', capitals:["Asmara"] },
    { names:["Estonia"],                   flagUrl:'https://flagcdn.com/w320/ee.png', capitals:["Tallinn"] },
    { names:["Eswatini"],                  flagUrl:'https://flagcdn.com/w320/sz.png', capitals:["Mbabane","Lobamba"] },
    { names:["Ethiopia"],                  flagUrl:'https://flagcdn.com/w320/et.png', capitals:["Addis Ababa"] },
    { names:["Fiji"],                      flagUrl:'https://flagcdn.com/w320/fj.png', capitals:["Suva"] },
    { names:["Finland"],                   flagUrl:'https://flagcdn.com/w320/fi.png', capitals:["Helsinki"] },
    { names:["France"],                    flagUrl:'https://flagcdn.com/w320/fr.png', capitals:["Paris"] },
    { names:["Gabon"],                     flagUrl:'https://flagcdn.com/w320/ga.png', capitals:["Libreville"] },
    { names:["Gambia"],                    flagUrl:'https://flagcdn.com/w320/gm.png', capitals:["Banjul"] },
    { names:["Georgia"],                   flagUrl:'https://flagcdn.com/w320/ge.png', capitals:["Tbilisi"] },
    { names:["Germany"],                   flagUrl:'https://flagcdn.com/w320/de.png', capitals:["Berlin"] },
    { names:["Ghana"],                     flagUrl:'https://flagcdn.com/w320/gh.png', capitals:["Accra"] },
    { names:["Greece"],                    flagUrl:'https://flagcdn.com/w320/gr.png', capitals:["Athens"] },
    { names:["Grenada"],                   flagUrl:'https://flagcdn.com/w320/gd.png', capitals:["St. George's"] },
    { names:["Guatemala"],                 flagUrl:'https://flagcdn.com/w320/gt.png', capitals:["Guatemala City"] },
    { names:["Guinea"],                    flagUrl:'https://flagcdn.com/w320/gn.png', capitals:["Conakry"] },
    { names:["Guinea-Bissau"],             flagUrl:'https://flagcdn.com/w320/gw.png', capitals:["Bissau"] },
    { names:["Guyana"],                    flagUrl:'https://flagcdn.com/w320/gy.png', capitals:["Georgetown"] },
    { names:["Haiti"],                     flagUrl:'https://flagcdn.com/w320/ht.png', capitals:["Port-au-Prince"] },
    { names:["Honduras"],                  flagUrl:'https://flagcdn.com/w320/hn.png', capitals:["Tegucigalpa"] },
    { names:["Hungary"],                   flagUrl:'https://flagcdn.com/w320/hu.png', capitals:["Budapest"] },
    { names:["Iceland"],                   flagUrl:'https://flagcdn.com/w320/is.png', capitals:["Reykjavík"] },
    { names:["India"],                     flagUrl:'https://flagcdn.com/w320/in.png', capitals:["New Delhi"] },
    { names:["Indonesia"],                 flagUrl:'https://flagcdn.com/w320/id.png', capitals:["Jakarta"] },
    { names:["Iran"],                      flagUrl:'https://flagcdn.com/w320/ir.png', capitals:["Tehran"] },
    { names:["Iraq"],                      flagUrl:'https://flagcdn.com/w320/iq.png', capitals:["Baghdad"] },
    { names:["Ireland"],                   flagUrl:'https://flagcdn.com/w320/ie.png', capitals:["Dublin"] },
    { names:["Israel"],                    flagUrl:'https://flagcdn.com/w320/il.png', capitals:["Jerusalem"] },
    { names:["Italy"],                     flagUrl:'https://flagcdn.com/w320/it.png', capitals:["Rome"] },
    { names:["Jamaica"],                   flagUrl:'https://flagcdn.com/w320/jm.png', capitals:["Kingston"] },
    { names:["Japan"],                     flagUrl:'https://flagcdn.com/w320/jp.png', capitals:["Tokyo"] },
    { names:["Jordan"],                    flagUrl:'https://flagcdn.com/w320/jo.png', capitals:["Amman"] },
    { names:["Kazakhstan"],                flagUrl:'https://flagcdn.com/w320/kz.png', capitals:["Astana"] },
    { names:["Kenya"],                     flagUrl:'https://flagcdn.com/w320/ke.png', capitals:["Nairobi"] },
    { names:["Kiribati"],                  flagUrl:'https://flagcdn.com/w320/ki.png', capitals:["Tarawa"] },
    { names:["Kuwait"],                    flagUrl:'https://flagcdn.com/w320/kw.png', capitals:["Kuwait City"] },
    { names:["Kyrgyzstan"],                flagUrl:'https://flagcdn.com/w320/kg.png', capitals:["Bishkek"] },
    { names:["Laos"],                      flagUrl:'https://flagcdn.com/w320/la.png', capitals:["Vientiane"] },
    { names:["Latvia"],                    flagUrl:'https://flagcdn.com/w320/lv.png', capitals:["Riga"] },
    { names:["Lebanon"],                   flagUrl:'https://flagcdn.com/w320/lb.png', capitals:["Beirut"] },
    { names:["Lesotho"],                   flagUrl:'https://flagcdn.com/w320/ls.png', capitals:["Maseru"] },
    { names:["Liberia"],                   flagUrl:'https://flagcdn.com/w320/lr.png', capitals:["Monrovia"] },
    { names:["Libya"],                     flagUrl:'https://flagcdn.com/w320/ly.png', capitals:["Tripoli"] },
    { names:["Liechtenstein"],             flagUrl:'https://flagcdn.com/w320/li.png', capitals:["Vaduz"] },
    { names:["Lithuania"],                 flagUrl:'https://flagcdn.com/w320/lt.png', capitals:["Vilnius"] },
    { names:["Luxembourg"],                flagUrl:'https://flagcdn.com/w320/lu.png', capitals:["Luxembourg City"] },
    { names:["Madagascar"],                flagUrl:'https://flagcdn.com/w320/mg.png', capitals:["Antananarivo"] },
    { names:["Malawi"],                    flagUrl:'https://flagcdn.com/w320/mw.png', capitals:["Lilongwe"] },
    { names:["Malaysia"],                  flagUrl:'https://flagcdn.com/w320/my.png', capitals:["Kuala Lumpur"] },
    { names:["Maldives"],                  flagUrl:'https://flagcdn.com/w320/mv.png', capitals:["Malé"] },
    { names:["Mali"],                      flagUrl:'https://flagcdn.com/w320/ml.png', capitals:["Bamako"] },
    { names:["Malta"],                     flagUrl:'https://flagcdn.com/w320/mt.png', capitals:["Valletta"] },
    { names:["Marshall Islands"],          flagUrl:'https://flagcdn.com/w320/mh.png', capitals:["Majuro"] },
    { names:["Mauritania"],                flagUrl:'https://flagcdn.com/w320/mr.png', capitals:["Nouakchott"] },
    { names:["Mauritius"],                 flagUrl:'https://flagcdn.com/w320/mu.png', capitals:["Port Louis"] },
    { names:["Mexico"],                    flagUrl:'https://flagcdn.com/w320/mx.png', capitals:["Mexico City"] },
    { names:["Micronesia"],                flagUrl:'https://flagcdn.com/w320/fm.png', capitals:["Palikir"] },
    { names:["Moldova"],                   flagUrl:'https://flagcdn.com/w320/md.png', capitals:["Chișinău"] },
    { names:["Monaco"],                    flagUrl:'https://flagcdn.com/w320/mc.png', capitals:["Monaco"] },
    { names:["Mongolia"],                  flagUrl:'https://flagcdn.com/w320/mn.png', capitals:["Ulaanbaatar"] },
    { names:["Montenegro"],                flagUrl:'https://flagcdn.com/w320/me.png', capitals:["Podgorica"] },
    { names:["Morocco"],                   flagUrl:'https://flagcdn.com/w320/ma.png', capitals:["Rabat"] },
    { names:["Mozambique"],                flagUrl:'https://flagcdn.com/w320/mz.png', capitals:["Maputo"] },
    { names:["Myanmar"],                   flagUrl:'https://flagcdn.com/w320/mm.png', capitals:["Naypyidaw"] },
    { names:["Namibia"],                   flagUrl:'https://flagcdn.com/w320/na.png', capitals:["Windhoek"] },
    { names:["Nauru"],                     flagUrl:'https://flagcdn.com/w320/nr.png', capitals:["Yaren"] },
    { names:["Nepal"],                     flagUrl:'https://flagcdn.com/w320/np.png', capitals:["Kathmandu"] },
    { names:["Netherlands"],               flagUrl:'https://flagcdn.com/w320/nl.png', capitals:["Amsterdam"] },
    { names:["New Zealand"],               flagUrl:'https://flagcdn.com/w320/nz.png', capitals:["Wellington"] },
    { names:["Nicaragua"],                 flagUrl:'https://flagcdn.com/w320/ni.png', capitals:["Managua"] },
    { names:["Niger"],                     flagUrl:'https://flagcdn.com/w320/ne.png', capitals:["Niamey"] },
    { names:["Nigeria"],                   flagUrl:'https://flagcdn.com/w320/ng.png', capitals:["Abuja"] },
    { names:["North Korea"],               flagUrl:'https://flagcdn.com/w320/kp.png', capitals:["Pyongyang"] },
    { names:["North Macedonia"],           flagUrl:'https://flagcdn.com/w320/mk.png', capitals:["Skopje"] },
    { names:["Norway"],                    flagUrl:'https://flagcdn.com/w320/no.png', capitals:["Oslo"] },
    { names:["Oman"],                      flagUrl:'https://flagcdn.com/w320/om.png', capitals:["Muscat"] },
    { names:["Pakistan"],                  flagUrl:'https://flagcdn.com/w320/pk.png', capitals:["Islamabad"] },
    { names:["Palau"],                     flagUrl:'https://flagcdn.com/w320/pw.png', capitals:["Ngerulmud"] },
    { names:["Panama"],                    flagUrl:'https://flagcdn.com/w320/pa.png', capitals:["Panama City"] },
    { names:["Papua New Guinea"],          flagUrl:'https://flagcdn.com/w320/pg.png', capitals:["Port Moresby"] },
    { names:["Paraguay"],                  flagUrl:'https://flagcdn.com/w320/py.png', capitals:["Asunción"] },
    { names:["Peru"],                      flagUrl:'https://flagcdn.com/w320/pe.png', capitals:["Lima"] },
    { names:["Philippines"],               flagUrl:'https://flagcdn.com/w320/ph.png', capitals:["Manila"] },
    { names:["Poland"],                    flagUrl:'https://flagcdn.com/w320/pl.png', capitals:["Warsaw"] },
    { names:["Portugal"],                  flagUrl:'https://flagcdn.com/w320/pt.png', capitals:["Lisbon"] },
    { names:["Qatar"],                     flagUrl:'https://flagcdn.com/w320/qa.png', capitals:["Doha"] },
    { names:["Republic Of The Congo"],     flagUrl:'https://flagcdn.com/w320/cg.png', capitals:["Brazzaville"] },
    { names:["Romania"],                   flagUrl:'https://flagcdn.com/w320/ro.png', capitals:["Bucharest"] },
    { names:["Russia"],                    flagUrl:'https://flagcdn.com/w320/ru.png', capitals:["Moscow"] },
    { names:["Rwanda"],                    flagUrl:'https://flagcdn.com/w320/rw.png', capitals:["Kigali"] },
    { names:["Saint Kitts And Nevis"],     flagUrl:'https://flagcdn.com/w320/kn.png', capitals:["Basseterre"] },
    { names:["Saint Lucia"],               flagUrl:'https://flagcdn.com/w320/lc.png', capitals:["Castries"] },
    { names:["Saint Vincent And The Grenadines"], flagUrl:'https://flagcdn.com/w320/vc.png', capitals:["Kingstown"] },
    { names:["Samoa"],                     flagUrl:'https://flagcdn.com/w320/ws.png', capitals:["Apia"] },
    { names:["San Marino"],                flagUrl:'https://flagcdn.com/w320/sm.png', capitals:["San Marino"] },
    { names:["Sao Tome And Principe"],     flagUrl:'https://flagcdn.com/w320/st.png', capitals:["São Tomé"] },
    { names:["Saudi Arabia"],              flagUrl:'https://flagcdn.com/w320/sa.png', capitals:["Riyadh"] },
    { names:["Senegal"],                   flagUrl:'https://flagcdn.com/w320/sn.png', capitals:["Dakar"] },
    { names:["Serbia"],                    flagUrl:'https://flagcdn.com/w320/rs.png', capitals:["Belgrade"] },
    { names:["Seychelles"],                flagUrl:'https://flagcdn.com/w320/sc.png', capitals:["Victoria"] },
    { names:["Sierra Leone"],              flagUrl:'https://flagcdn.com/w320/sl.png', capitals:["Freetown"] },
    { names:["Singapore"],                 flagUrl:'https://flagcdn.com/w320/sg.png', capitals:["Singapore"] },
    { names:["Slovakia"],                  flagUrl:'https://flagcdn.com/w320/sk.png', capitals:["Bratislava"] },
    { names:["Slovenia"],                  flagUrl:'https://flagcdn.com/w320/si.png', capitals:["Ljubljana"] },
    { names:["Solomon Islands"],           flagUrl:'https://flagcdn.com/w320/sb.png', capitals:["Honiara"] },
    { names:["Somalia"],                   flagUrl:'https://flagcdn.com/w320/so.png', capitals:["Mogadishu"] },
    { names:["South Africa"],              flagUrl:'https://flagcdn.com/w320/za.png', capitals:["Pretoria","Bloemfontein","Cape Town"] },
    { names:["South Korea"],               flagUrl:'https://flagcdn.com/w320/kr.png', capitals:["Seoul"] },
    { names:["South Sudan"],               flagUrl:'https://flagcdn.com/w320/ss.png', capitals:["Juba"] },
    { names:["Spain"],                     flagUrl:'https://flagcdn.com/w320/es.png', capitals:["Madrid"] },
    { names:["Sri Lanka"],                 flagUrl:'https://flagcdn.com/w320/lk.png', capitals:["Sri Jayawardenepura Kotte","Colombo"] },
    { names:["Sudan"],                     flagUrl:'https://flagcdn.com/w320/sd.png', capitals:["Khartoum"] },
    { names:["Suriname"],                  flagUrl:'https://flagcdn.com/w320/sr.png', capitals:["Paramaribo"] },
    { names:["Sweden"],                    flagUrl:'https://flagcdn.com/w320/se.png', capitals:["Stockholm"] },
    { names:["Switzerland"],               flagUrl:'https://flagcdn.com/w320/ch.png', capitals:["Bern"] },
    { names:["Syria"],                     flagUrl:'https://flagcdn.com/w320/sy.png', capitals:["Damascus"] },
    { names:["Tajikistan"],                flagUrl:'https://flagcdn.com/w320/tj.png', capitals:["Dushanbe"] },
    { names:["Tanzania"],                  flagUrl:'https://flagcdn.com/w320/tz.png', capitals:["Dodoma"] },
    { names:["Thailand"],                  flagUrl:'https://flagcdn.com/w320/th.png', capitals:["Bangkok"] },
    { names:["Timor-Leste"],               flagUrl:'https://flagcdn.com/w320/tl.png', capitals:["Dili"] },
    { names:["Togo"],                      flagUrl:'https://flagcdn.com/w320/tg.png', capitals:["Lomé"] },
    { names:["Tonga"],                     flagUrl:'https://flagcdn.com/w320/to.png', capitals:["Nuku'alofa"] },
    { names:["Trinidad And Tobago"],       flagUrl:'https://flagcdn.com/w320/tt.png', capitals:["Port of Spain"] },
    { names:["Tunisia"],                   flagUrl:'https://flagcdn.com/w320/tn.png', capitals:["Tunis"] },
    { names:["Turkey"],                    flagUrl:'https://flagcdn.com/w320/tr.png', capitals:["Ankara"] },
    { names:["Turkmenistan"],              flagUrl:'https://flagcdn.com/w320/tm.png', capitals:["Ashgabat"] },
    { names:["Tuvalu"],                    flagUrl:'https://flagcdn.com/w320/tv.png', capitals:["Funafuti"] },
    { names:["Uganda"],                    flagUrl:'https://flagcdn.com/w320/ug.png', capitals:["Kampala"] },
    { names:["Ukraine"],                   flagUrl:'https://flagcdn.com/w320/ua.png', capitals:["Kyiv"] },
    { names:["United Arab Emirates","UAE"],      flagUrl:'https://flagcdn.com/w320/ae.png', capitals:["Abu Dhabi"] },
    { names:["United Kingdom","UK"],            flagUrl:'https://flagcdn.com/w320/gb.png', capitals:["London"] },
    { names:["United States Of America","USA"], flagUrl:'https://flagcdn.com/w320/us.png', capitals:["Washington D.C."] },
    { names:["Uruguay"],                   flagUrl:'https://flagcdn.com/w320/uy.png', capitals:["Montevideo"] },
    { names:["Uzbekistan"],                flagUrl:'https://flagcdn.com/w320/uz.png', capitals:["Tashkent"] },
    { names:["Vanuatu"],                   flagUrl:'https://flagcdn.com/w320/vu.png', capitals:["Port Vila"] },
    { names:["Venezuela"],                 flagUrl:'https://flagcdn.com/w320/ve.png', capitals:["Caracas"] },
    { names:["Vietnam"],                   flagUrl:'https://flagcdn.com/w320/vn.png', capitals:["Hanoi"] },
    { names:["Yemen"],                     flagUrl:'https://flagcdn.com/w320/ye.png', capitals:["Sana'a"] },
    { names:["Zambia"],                    flagUrl:'https://flagcdn.com/w320/zm.png', capitals:["Lusaka"] },
    { names:["Zimbabwe"],                  flagUrl:'https://flagcdn.com/w320/zw.png', capitals:["Harare"] },
    // not UN-recognized
    { names:["Taiwan"],                    flagUrl:'https://flagcdn.com/w320/tw.png', capitals:["Taipei"] },
    { names:["Kosovo"],                    flagUrl:'https://flagcdn.com/w320/xk.png', capitals:["Pristina"] },
    { names:["Palestine"],                 flagUrl:'https://flagcdn.com/w320/ps.png', capitals:["East Jerusalem","Ramallah"] }
  ];
  window.countries = countries;
})();
