;(function(){
  const countries = [
    { names:["Afghanistan"],               flagUrl:'https://flagcdn.com/af.svg', capitals:["Kabul"] },
    { names:["Albania"],                   flagUrl:'https://flagcdn.com/al.svg', capitals:["Tirana"] },
    { names:["Algeria"],                   flagUrl:'https://flagcdn.com/dz.svg', capitals:["Algiers"] },
    { names:["Andorra"],                   flagUrl:'https://flagcdn.com/ad.svg', capitals:["Andorra la Vella"] },
    { names:["Angola"],                    flagUrl:'https://flagcdn.com/ao.svg', capitals:["Luanda"] },
    { names:["Antigua And Barbuda"],       flagUrl:'https://flagcdn.com/ag.svg', capitals:["St. John's"] },
    { names:["Argentina"],                 flagUrl:'https://flagcdn.com/ar.svg', capitals:["Buenos Aires"] },
    { names:["Armenia"],                   flagUrl:'https://flagcdn.com/am.svg', capitals:["Yerevan"] },
    { names:["Australia"],                 flagUrl:'https://flagcdn.com/au.svg', capitals:["Canberra"] },
    { names:["Austria"],                   flagUrl:'https://flagcdn.com/at.svg', capitals:["Vienna"] },
    { names:["Azerbaijan"],                flagUrl:'https://flagcdn.com/az.svg', capitals:["Baku"] },
    { names:["Bahamas"],                   flagUrl:'https://flagcdn.com/bs.svg', capitals:["Nassau"] },
    { names:["Bahrain"],                   flagUrl:'https://flagcdn.com/bh.svg', capitals:["Manama"] },
    { names:["Bangladesh"],                flagUrl:'https://flagcdn.com/bd.svg', capitals:["Dhaka"] },
    { names:["Barbados"],                  flagUrl:'https://flagcdn.com/bb.svg', capitals:["Bridgetown"] },
    { names:["Belarus"],                   flagUrl:'https://flagcdn.com/by.svg', capitals:["Minsk"] },
    { names:["Belgium"],                   flagUrl:'https://flagcdn.com/be.svg', capitals:["Brussels"] },
    { names:["Belize"],                    flagUrl:'https://flagcdn.com/bz.svg', capitals:["Belmopan"] },
    { names:["Benin"],                     flagUrl:'https://flagcdn.com/bj.svg', capitals:["Porto-Novo"] },
    { names:["Bhutan"],                    flagUrl:'https://flagcdn.com/bt.svg', capitals:["Thimphu"] },
    { names:["Bolivia"],                   flagUrl:'https://flagcdn.com/bo.svg', capitals:["Sucre","La Paz"] },
    { names:["Bosnia And Herzegovina"],    flagUrl:'https://flagcdn.com/ba.svg', capitals:["Sarajevo"] },
    { names:["Botswana"],                  flagUrl:'https://flagcdn.com/bw.svg', capitals:["Gaborone"] },
    { names:["Brazil"],                    flagUrl:'https://flagcdn.com/br.svg', capitals:["Brasília"] },
    { names:["Brunei"],                    flagUrl:'https://flagcdn.com/bn.svg', capitals:["Bandar Seri Begawan"] },
    { names:["Bulgaria"],                  flagUrl:'https://flagcdn.com/bg.svg', capitals:["Sofia"] },
    { names:["Burkina Faso"],              flagUrl:'https://flagcdn.com/bf.svg', capitals:["Ouagadougou"] },
    { names:["Burundi"],                   flagUrl:'https://flagcdn.com/bi.svg', capitals:["Gitega"] },
    { names:["Côte d'Ivoire","Ivory Coast"], flagUrl:'https://flagcdn.com/ci.svg', capitals:["Yamoussoukro"] },
    { names:["Cabo Verde"],                flagUrl:'https://flagcdn.com/cv.svg', capitals:["Praia"] },
    { names:["Cambodia"],                  flagUrl:'https://flagcdn.com/kh.svg', capitals:["Phnom Penh"] },
    { names:["Cameroon"],                  flagUrl:'https://flagcdn.com/cm.svg', capitals:["Yaoundé"] },
    { names:["Canada"],                    flagUrl:'https://flagcdn.com/ca.svg', capitals:["Ottawa"] },
    { names:["Central African Republic","CAR"], flagUrl:'https://flagcdn.com/cf.svg', capitals:["Bangui"] },
    { names:["Chad"],                      flagUrl:'https://flagcdn.com/td.svg', capitals:["N'Djamena"] },
    { names:["Chile"],                     flagUrl:'https://flagcdn.com/cl.svg', capitals:["Santiago"] },
    { names:["China"],                     flagUrl:'https://flagcdn.com/cn.svg', capitals:["Beijing"] },
    { names:["Colombia"],                  flagUrl:'https://flagcdn.com/co.svg', capitals:["Bogotá"] },
    { names:["Comoros"],                   flagUrl:'https://flagcdn.com/km.svg', capitals:["Moroni"] },
    { names:["Costa Rica"],                flagUrl:'https://flagcdn.com/cr.svg', capitals:["San José"] },
    { names:["Croatia"],                   flagUrl:'https://flagcdn.com/hr.svg', capitals:["Zagreb"] },
    { names:["Cuba"],                      flagUrl:'https://flagcdn.com/cu.svg', capitals:["Havana"] },
    { names:["Cyprus"],                    flagUrl:'https://flagcdn.com/cy.svg', capitals:["Nicosia"] },
    { names:["Czech Republic","Czechia"],  flagUrl:'https://flagcdn.com/cz.svg', capitals:["Prague"] },
    { names:["Democratic Republic Of The Congo","DRC", "DR Congo"], flagUrl:'https://flagcdn.com/cd.svg', capitals:["Kinshasa"] },
    { names:["Denmark"],                   flagUrl:'https://flagcdn.com/dk.svg', capitals:["Copenhagen"] },
    { names:["Djibouti"],                  flagUrl:'https://flagcdn.com/dj.svg', capitals:["Djibouti"] },
    { names:["Dominica"],                  flagUrl:'https://flagcdn.com/dm.svg', capitals:["Roseau"] },
    { names:["Dominican Republic"],        flagUrl:'https://flagcdn.com/do.svg', capitals:["Santo Domingo"] },
    { names:["Ecuador"],                   flagUrl:'https://flagcdn.com/ec.svg', capitals:["Quito"] },
    { names:["Egypt"],                     flagUrl:'https://flagcdn.com/eg.svg', capitals:["Cairo"] },
    { names:["El Salvador"],               flagUrl:'https://flagcdn.com/sv.svg', capitals:["San Salvador"] },
    { names:["Equatorial Guinea"],         flagUrl:'https://flagcdn.com/gq.svg', capitals:["Malabo","Oyala"] },
    { names:["Eritrea"],                   flagUrl:'https://flagcdn.com/er.svg', capitals:["Asmara"] },
    { names:["Estonia"],                   flagUrl:'https://flagcdn.com/ee.svg', capitals:["Tallinn"] },
    { names:["Eswatini", "Swaziland"],                  flagUrl:'https://flagcdn.com/sz.svg', capitals:["Mbabane","Lobamba"] },
    { names:["Ethiopia"],                  flagUrl:'https://flagcdn.com/et.svg', capitals:["Addis Ababa"] },
    { names:["Fiji"],                      flagUrl:'https://flagcdn.com/fj.svg', capitals:["Suva"] },
    { names:["Finland"],                   flagUrl:'https://flagcdn.com/fi.svg', capitals:["Helsinki"] },
    { names:["France"],                    flagUrl:'https://flagcdn.com/fr.svg', capitals:["Paris"] },
    { names:["Gabon"],                     flagUrl:'https://flagcdn.com/ga.svg', capitals:["Libreville"] },
    { names:["Gambia", "The Gambia"],                    flagUrl:'https://flagcdn.com/gm.svg', capitals:["Banjul"] },
    { names:["Georgia"],                   flagUrl:'https://flagcdn.com/ge.svg', capitals:["Tbilisi"] },
    { names:["Germany"],                   flagUrl:'https://flagcdn.com/de.svg', capitals:["Berlin"] },
    { names:["Ghana"],                     flagUrl:'https://flagcdn.com/gh.svg', capitals:["Accra"] },
    { names:["Greece"],                    flagUrl:'https://flagcdn.com/gr.svg', capitals:["Athens"] },
    { names:["Grenada"],                   flagUrl:'https://flagcdn.com/gd.svg', capitals:["St. George's"] },
    { names:["Guatemala"],                 flagUrl:'https://flagcdn.com/gt.svg', capitals:["Guatemala City"] },
    { names:["Guinea"],                    flagUrl:'https://flagcdn.com/gn.svg', capitals:["Conakry"] },
    { names:["Guinea-Bissau"],             flagUrl:'https://flagcdn.com/gw.svg', capitals:["Bissau"] },
    { names:["Guyana"],                    flagUrl:'https://flagcdn.com/gy.svg', capitals:["Georgetown"] },
    { names:["Haiti"],                     flagUrl:'https://flagcdn.com/ht.svg', capitals:["Port-au-Prince"] },
    { names:["Honduras"],                  flagUrl:'https://flagcdn.com/hn.svg', capitals:["Tegucigalpa"] },
    { names:["Hungary"],                   flagUrl:'https://flagcdn.com/hu.svg', capitals:["Budapest"] },
    { names:["Iceland"],                   flagUrl:'https://flagcdn.com/is.svg', capitals:["Reykjavík"] },
    { names:["India"],                     flagUrl:'https://flagcdn.com/in.svg', capitals:["New Delhi"] },
    { names:["Indonesia"],                 flagUrl:'https://flagcdn.com/id.svg', capitals:["Jakarta"] },
    { names:["Iran"],                      flagUrl:'https://flagcdn.com/ir.svg', capitals:["Tehran"] },
    { names:["Iraq"],                      flagUrl:'https://flagcdn.com/iq.svg', capitals:["Baghdad"] },
    { names:["Ireland"],                   flagUrl:'https://flagcdn.com/ie.svg', capitals:["Dublin"] },
    { names:["Israel"],                    flagUrl:'https://flagcdn.com/il.svg', capitals:["Jerusalem"] },
    { names:["Italy"],                     flagUrl:'https://flagcdn.com/it.svg', capitals:["Rome"] },
    { names:["Jamaica"],                   flagUrl:'https://flagcdn.com/jm.svg', capitals:["Kingston"] },
    { names:["Japan"],                     flagUrl:'https://flagcdn.com/jp.svg', capitals:["Tokyo"] },
    { names:["Jordan"],                    flagUrl:'https://flagcdn.com/jo.svg', capitals:["Amman"] },
    { names:["Kazakhstan"],                flagUrl:'https://flagcdn.com/kz.svg', capitals:["Astana"] },
    { names:["Kenya"],                     flagUrl:'https://flagcdn.com/ke.svg', capitals:["Nairobi"] },
    { names:["Kiribati"],                  flagUrl:'https://flagcdn.com/ki.svg', capitals:["Tarawa"] },
    { names:["Kuwait"],                    flagUrl:'https://flagcdn.com/kw.svg', capitals:["Kuwait City"] },
    { names:["Kyrgyzstan"],                flagUrl:'https://flagcdn.com/kg.svg', capitals:["Bishkek"] },
    { names:["Laos"],                      flagUrl:'https://flagcdn.com/la.svg', capitals:["Vientiane"] },
    { names:["Latvia"],                    flagUrl:'https://flagcdn.com/lv.svg', capitals:["Riga"] },
    { names:["Lebanon"],                   flagUrl:'https://flagcdn.com/lb.svg', capitals:["Beirut"] },
    { names:["Lesotho"],                   flagUrl:'https://flagcdn.com/ls.svg', capitals:["Maseru"] },
    { names:["Liberia"],                   flagUrl:'https://flagcdn.com/lr.svg', capitals:["Monrovia"] },
    { names:["Libya"],                     flagUrl:'https://flagcdn.com/ly.svg', capitals:["Tripoli"] },
    { names:["Liechtenstein"],             flagUrl:'https://flagcdn.com/li.svg', capitals:["Vaduz"] },
    { names:["Lithuania"],                 flagUrl:'https://flagcdn.com/lt.svg', capitals:["Vilnius"] },
    { names:["Luxembourg"],                flagUrl:'https://flagcdn.com/lu.svg', capitals:["Luxembourg City"] },
    { names:["Madagascar"],                flagUrl:'https://flagcdn.com/mg.svg', capitals:["Antananarivo"] },
    { names:["Malawi"],                    flagUrl:'https://flagcdn.com/mw.svg', capitals:["Lilongwe"] },
    { names:["Malaysia"],                  flagUrl:'https://flagcdn.com/my.svg', capitals:["Kuala Lumpur"] },
    { names:["Maldives"],                  flagUrl:'https://flagcdn.com/mv.svg', capitals:["Malé"] },
    { names:["Mali"],                      flagUrl:'https://flagcdn.com/ml.svg', capitals:["Bamako"] },
    { names:["Malta"],                     flagUrl:'https://flagcdn.com/mt.svg', capitals:["Valletta"] },
    { names:["Marshall Islands"],          flagUrl:'https://flagcdn.com/mh.svg', capitals:["Majuro"] },
    { names:["Mauritania"],                flagUrl:'https://flagcdn.com/mr.svg', capitals:["Nouakchott"] },
    { names:["Mauritius"],                 flagUrl:'https://flagcdn.com/mu.svg', capitals:["Port Louis"] },
    { names:["Mexico"],                    flagUrl:'https://flagcdn.com/mx.svg', capitals:["Mexico City"] },
    { names:["Micronesia"],                flagUrl:'https://flagcdn.com/fm.svg', capitals:["Palikir"] },
    { names:["Moldova"],                   flagUrl:'https://flagcdn.com/md.svg', capitals:["Chișinău"] },
    { names:["Monaco"],                    flagUrl:'https://flagcdn.com/mc.svg', capitals:["Monaco"] },
    { names:["Mongolia"],                  flagUrl:'https://flagcdn.com/mn.svg', capitals:["Ulaanbaatar"] },
    { names:["Montenegro"],                flagUrl:'https://flagcdn.com/me.svg', capitals:["Podgorica"] },
    { names:["Morocco"],                   flagUrl:'https://flagcdn.com/ma.svg', capitals:["Rabat"] },
    { names:["Mozambique"],                flagUrl:'https://flagcdn.com/mz.svg', capitals:["Maputo"] },
    { names:["Myanmar"],                   flagUrl:'https://flagcdn.com/mm.svg', capitals:["Naypyidaw"] },
    { names:["Namibia"],                   flagUrl:'https://flagcdn.com/na.svg', capitals:["Windhoek"] },
    { names:["Nauru"],                     flagUrl:'https://flagcdn.com/nr.svg', capitals:["Yaren"] },
    { names:["Nepal"],                     flagUrl:'https://flagcdn.com/np.svg', capitals:["Kathmandu"] },
    { names:["Netherlands"],               flagUrl:'https://flagcdn.com/nl.svg', capitals:["Amsterdam"] },
    { names:["New Zealand"],               flagUrl:'https://flagcdn.com/nz.svg', capitals:["Wellington"] },
    { names:["Nicaragua"],                 flagUrl:'https://flagcdn.com/ni.svg', capitals:["Managua"] },
    { names:["Niger"],                     flagUrl:'https://flagcdn.com/ne.svg', capitals:["Niamey"] },
    { names:["Nigeria"],                   flagUrl:'https://flagcdn.com/ng.svg', capitals:["Abuja"] },
    { names:["North Korea"],               flagUrl:'https://flagcdn.com/kp.svg', capitals:["Pyongyang"] },
    { names:["North Macedonia"],           flagUrl:'https://flagcdn.com/mk.svg', capitals:["Skopje"] },
    { names:["Norway"],                    flagUrl:'https://flagcdn.com/no.svg', capitals:["Oslo"] },
    { names:["Oman"],                      flagUrl:'https://flagcdn.com/om.svg', capitals:["Muscat"] },
    { names:["Pakistan"],                  flagUrl:'https://flagcdn.com/pk.svg', capitals:["Islamabad"] },
    { names:["Palau"],                     flagUrl:'https://flagcdn.com/pw.svg', capitals:["Ngerulmud"] },
    { names:["Panama"],                    flagUrl:'https://flagcdn.com/pa.svg', capitals:["Panama City"] },
    { names:["Papua New Guinea"],          flagUrl:'https://flagcdn.com/pg.svg', capitals:["Port Moresby"] },
    { names:["Paraguay"],                  flagUrl:'https://flagcdn.com/py.svg', capitals:["Asunción"] },
    { names:["Peru"],                      flagUrl:'https://flagcdn.com/pe.svg', capitals:["Lima"] },
    { names:["Philippines"],               flagUrl:'https://flagcdn.com/ph.svg', capitals:["Manila"] },
    { names:["Poland"],                    flagUrl:'https://flagcdn.com/pl.svg', capitals:["Warsaw"] },
    { names:["Portugal"],                  flagUrl:'https://flagcdn.com/pt.svg', capitals:["Lisbon"] },
    { names:["Qatar"],                     flagUrl:'https://flagcdn.com/qa.svg', capitals:["Doha"] },
    { names:["Republic Of The Congo"],     flagUrl:'https://flagcdn.com/cg.svg', capitals:["Brazzaville"] },
    { names:["Romania"],                   flagUrl:'https://flagcdn.com/ro.svg', capitals:["Bucharest"] },
    { names:["Russia"],                    flagUrl:'https://flagcdn.com/ru.svg', capitals:["Moscow"] },
    { names:["Rwanda"],                    flagUrl:'https://flagcdn.com/rw.svg', capitals:["Kigali"] },
    { names:["Saint Kitts And Nevis"],     flagUrl:'https://flagcdn.com/kn.svg', capitals:["Basseterre"] },
    { names:["Saint Lucia"],               flagUrl:'https://flagcdn.com/lc.svg', capitals:["Castries"] },
    { names:["Saint Vincent And The Grenadines"], flagUrl:'https://flagcdn.com/vc.svg', capitals:["Kingstown"] },
    { names:["Samoa"],                     flagUrl:'https://flagcdn.com/ws.svg', capitals:["Apia"] },
    { names:["San Marino"],                flagUrl:'https://flagcdn.com/sm.svg', capitals:["San Marino"] },
    { names:["Sao Tome And Principe"],     flagUrl:'https://flagcdn.com/st.svg', capitals:["São Tomé"] },
    { names:["Saudi Arabia"],              flagUrl:'https://flagcdn.com/sa.svg', capitals:["Riyadh"] },
    { names:["Senegal"],                   flagUrl:'https://flagcdn.com/sn.svg', capitals:["Dakar"] },
    { names:["Serbia"],                    flagUrl:'https://flagcdn.com/rs.svg', capitals:["Belgrade"] },
    { names:["Seychelles"],                flagUrl:'https://flagcdn.com/sc.svg', capitals:["Victoria"] },
    { names:["Sierra Leone"],              flagUrl:'https://flagcdn.com/sl.svg', capitals:["Freetown"] },
    { names:["Singapore"],                 flagUrl:'https://flagcdn.com/sg.svg', capitals:["Singapore"] },
    { names:["Slovakia"],                  flagUrl:'https://flagcdn.com/sk.svg', capitals:["Bratislava"] },
    { names:["Slovenia"],                  flagUrl:'https://flagcdn.com/si.svg', capitals:["Ljubljana"] },
    { names:["Solomon Islands"],           flagUrl:'https://flagcdn.com/sb.svg', capitals:["Honiara"] },
    { names:["Somalia"],                   flagUrl:'https://flagcdn.com/so.svg', capitals:["Mogadishu"] },
    { names:["South Africa"],              flagUrl:'https://flagcdn.com/za.svg', capitals:["Pretoria","Bloemfontein","Cape Town"] },
    { names:["South Korea"],               flagUrl:'https://flagcdn.com/kr.svg', capitals:["Seoul"] },
    { names:["South Sudan"],               flagUrl:'https://flagcdn.com/ss.svg', capitals:["Juba"] },
    { names:["Spain"],                     flagUrl:'https://flagcdn.com/es.svg', capitals:["Madrid"] },
    { names:["Sri Lanka"],                 flagUrl:'https://flagcdn.com/lk.svg', capitals:["Sri Jayawardenepura Kotte","Colombo"] },
    { names:["Sudan"],                     flagUrl:'https://flagcdn.com/sd.svg', capitals:["Khartoum"] },
    { names:["Suriname"],                  flagUrl:'https://flagcdn.com/sr.svg', capitals:["Paramaribo"] },
    { names:["Sweden"],                    flagUrl:'https://flagcdn.com/se.svg', capitals:["Stockholm"] },
    { names:["Switzerland"],               flagUrl:'https://flagcdn.com/ch.svg', capitals:["Bern"] },
    { names:["Syria"],                     flagUrl:'https://flagcdn.com/sy.svg', capitals:["Damascus"] },
    { names:["Tajikistan"],                flagUrl:'https://flagcdn.com/tj.svg', capitals:["Dushanbe"] },
    { names:["Tanzania"],                  flagUrl:'https://flagcdn.com/tz.svg', capitals:["Dodoma"] },
    { names:["Thailand"],                  flagUrl:'https://flagcdn.com/th.svg', capitals:["Bangkok"] },
    { names:["Timor-Leste"],               flagUrl:'https://flagcdn.com/tl.svg', capitals:["Dili"] },
    { names:["Togo"],                      flagUrl:'https://flagcdn.com/tg.svg', capitals:["Lomé"] },
    { names:["Tonga"],                     flagUrl:'https://flagcdn.com/to.svg', capitals:["Nuku'alofa"] },
    { names:["Trinidad And Tobago"],       flagUrl:'https://flagcdn.com/tt.svg', capitals:["Port of Spain"] },
    { names:["Tunisia"],                   flagUrl:'https://flagcdn.com/tn.svg', capitals:["Tunis"] },
    { names:["Turkey"],                    flagUrl:'https://flagcdn.com/tr.svg', capitals:["Ankara"] },
    { names:["Turkmenistan"],              flagUrl:'https://flagcdn.com/tm.svg', capitals:["Ashgabat"] },
    { names:["Tuvalu"],                    flagUrl:'https://flagcdn.com/tv.svg', capitals:["Funafuti"] },
    { names:["Uganda"],                    flagUrl:'https://flagcdn.com/ug.svg', capitals:["Kampala"] },
    { names:["Ukraine"],                   flagUrl:'https://flagcdn.com/ua.svg', capitals:["Kyiv"] },
    { names:["United Arab Emirates","UAE"],      flagUrl:'https://flagcdn.com/ae.svg', capitals:["Abu Dhabi"] },
    { names:["United Kingdom","UK"],            flagUrl:'https://flagcdn.com/gb.svg', capitals:["London"] },
    { names:["United States Of America","USA", "US"], flagUrl:'https://flagcdn.com/us.svg', capitals:["Washington D.C."] },
    { names:["Uruguay"],                   flagUrl:'https://flagcdn.com/uy.svg', capitals:["Montevideo"] },
    { names:["Uzbekistan"],                flagUrl:'https://flagcdn.com/uz.svg', capitals:["Tashkent"] },
    { names:["Vanuatu"],                   flagUrl:'https://flagcdn.com/vu.svg', capitals:["Port Vila"] },
    { names:["Venezuela"],                 flagUrl:'https://flagcdn.com/ve.svg', capitals:["Caracas"] },
    { names:["Vietnam", "Viet Nam"],                   flagUrl:'https://flagcdn.com/vn.svg', capitals:["Hanoi"] },
    { names:["Yemen"],                     flagUrl:'https://flagcdn.com/ye.svg', capitals:["Sana'a"] },
    { names:["Zambia"],                    flagUrl:'https://flagcdn.com/zm.svg', capitals:["Lusaka"] },
    { names:["Zimbabwe"],                  flagUrl:'https://flagcdn.com/zw.svg', capitals:["Harare"] },
    // not UN-recognized
    { names:["Taiwan", "Chinese Taipei"],                    flagUrl:'https://flagcdn.com/tw.svg', capitals:["Taipei"] },
    { names:["Kosovo"],                    flagUrl:'https://flagcdn.com/xk.svg', capitals:["Pristina"] },
    { names:["Palestine"],                 flagUrl:'https://flagcdn.com/ps.svg', capitals:["East Jerusalem","Ramallah"] }
  ];
  window.countries = countries;
})();
