;(function(){
  const states = [
    { names:["Alabama"],               flagUrl:"https://flagcdn.com/us-al.svg", capitals:["Montgomery"] },
    { names:["Alaska"],                flagUrl:"https://flagcdn.com/us-ak.svg", capitals:["Juneau"] },
    { names:["Arizona"],               flagUrl:"https://flagcdn.com/us-az.svg", capitals:["Phoenix"] },
    { names:["Arkansas"],              flagUrl:"https://flagcdn.com/us-ar.svg", capitals:["Little Rock"] },
    { names:["California"],            flagUrl:"https://flagcdn.com/us-ca.svg", capitals:["Sacramento"] },
    { names:["Colorado"],              flagUrl:"https://flagcdn.com/us-co.svg", capitals:["Denver"] },
    { names:["Connecticut"],           flagUrl:"https://flagcdn.com/us-ct.svg", capitals:["Hartford"] },
    { names:["Delaware"],              flagUrl:"https://flagcdn.com/us-de.svg", capitals:["Dover"] },
    { names:["Florida"],               flagUrl:"https://flagcdn.com/us-fl.svg", capitals:["Tallahassee"] },
    { names:["Georgia"],               flagUrl:"https://flagcdn.com/us-ga.svg", capitals:["Atlanta"] },
    { names:["Hawaii"],                flagUrl:"https://flagcdn.com/us-hi.svg", capitals:["Honolulu"] },
    { names:["Idaho"],                 flagUrl:"https://flagcdn.com/us-id.svg", capitals:["Boise"] },
    { names:["Illinois"],              flagUrl:"https://flagcdn.com/us-il.svg", capitals:["Springfield"] },
    { names:["Indiana"],               flagUrl:"https://flagcdn.com/us-in.svg", capitals:["Indianapolis"] },
    { names:["Iowa"],                  flagUrl:"https://flagcdn.com/us-ia.svg", capitals:["Des Moines"] },
    { names:["Kansas"],                flagUrl:"https://flagcdn.com/us-ks.svg", capitals:["Topeka"] },
    { names:["Kentucky"],              flagUrl:"https://flagcdn.com/us-ky.svg", capitals:["Frankfort"] },
    { names:["Louisiana"],             flagUrl:"https://flagcdn.com/us-la.svg", capitals:["Baton Rouge"] },
    { names:["Maine"],                 flagUrl:"https://flagcdn.com/us-me.svg", capitals:["Augusta"] },
    { names:["Maryland"],              flagUrl:"https://flagcdn.com/us-md.svg", capitals:["Annapolis"] },
    { names:["Massachusetts"],         flagUrl:"https://flagcdn.com/us-ma.svg", capitals:["Boston"] },
    { names:["Michigan"],              flagUrl:"https://flagcdn.com/us-mi.svg", capitals:["Lansing"] },
    { names:["Minnesota"],             flagUrl:"https://flagcdn.com/us-mn.svg", capitals:["Saint Paul"] },
    { names:["Mississippi"],           flagUrl:"https://flagcdn.com/us-ms.svg", capitals:["Jackson"] },
    { names:["Missouri"],              flagUrl:"https://flagcdn.com/us-mo.svg", capitals:["Jefferson City"] },
    { names:["Montana"],               flagUrl:"https://flagcdn.com/us-mt.svg", capitals:["Helena"] },
    { names:["Nebraska"],              flagUrl:"https://flagcdn.com/us-ne.svg", capitals:["Lincoln"] },
    { names:["Nevada"],                flagUrl:"https://flagcdn.com/us-nv.svg", capitals:["Carson City"] },
    { names:["New Hampshire"],         flagUrl:"https://flagcdn.com/us-nh.svg", capitals:["Concord"] },
    { names:["New Jersey"],            flagUrl:"https://flagcdn.com/us-nj.svg", capitals:["Trenton"] },
    { names:["New Mexico"],            flagUrl:"https://flagcdn.com/us-nm.svg", capitals:["Santa Fe"] },
    { names:["New York"],              flagUrl:"https://flagcdn.com/us-ny.svg", capitals:["Albany"] },
    { names:["North Carolina"],        flagUrl:"https://flagcdn.com/us-nc.svg", capitals:["Raleigh"] },
    { names:["North Dakota"],          flagUrl:"https://flagcdn.com/us-nd.svg", capitals:["Bismarck"] },
    { names:["Ohio"],                  flagUrl:"https://flagcdn.com/us-oh.svg", capitals:["Columbus"] },
    { names:["Oklahoma"],              flagUrl:"https://flagcdn.com/us-ok.svg", capitals:["Oklahoma City"] },
    { names:["Oregon"],                flagUrl:"https://flagcdn.com/us-or.svg", capitals:["Salem"] },
    { names:["Pennsylvania"],          flagUrl:"https://flagcdn.com/us-pa.svg", capitals:["Harrisburg"] },
    { names:["Rhode Island"],          flagUrl:"https://flagcdn.com/us-ri.svg", capitals:["Providence"] },
    { names:["South Carolina"],        flagUrl:"https://flagcdn.com/us-sc.svg", capitals:["Columbia"] },
    { names:["South Dakota"],          flagUrl:"https://flagcdn.com/us-sd.svg", capitals:["Pierre"] },
    { names:["Tennessee"],             flagUrl:"https://flagcdn.com/us-tn.svg", capitals:["Nashville"] },
    { names:["Texas"],                 flagUrl:"https://flagcdn.com/us-tx.svg", capitals:["Austin"] },
    { names:["Utah"],                  flagUrl:"https://flagcdn.com/us-ut.svg", capitals:["Salt Lake City"] },
    { names:["Vermont"],               flagUrl:"https://flagcdn.com/us-vt.svg", capitals:["Montpelier"] },
    { names:["Virginia"],              flagUrl:"https://flagcdn.com/us-va.svg", capitals:["Richmond"] },
    { names:["Washington"],            flagUrl:"https://flagcdn.com/us-wa.svg", capitals:["Olympia"] },
    { names:["West Virginia"],         flagUrl:"https://flagcdn.com/us-wv.svg", capitals:["Charleston"] },
    { names:["Wisconsin"],             flagUrl:"https://flagcdn.com/us-wi.svg", capitals:["Madison"] },
    { names:["Wyoming"],               flagUrl:"https://flagcdn.com/us-wy.svg", capitals:["Cheyenne"] }
  ];
  window.states = states;
})();
